"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/
"""

from pathlib import Path


# ==========================================================
# BASE
# ==========================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================================================
# SECURITY
# ==========================================================

SECRET_KEY = (
    "django-insecure-e3nn6_faorsklka@i7l_y"
    "^pu36b^zol-py$ezb#+pi9tn8vebz"
)

DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "192.168.18.48",
    "192.168.18.55",
    "192.168.18.16",
    "192.168.18.47",
    "192.168.18.22",
    "*",
]


# ==========================================================
# APPLICATIONS
# ==========================================================

INSTALLED_APPS = [
    "daphne",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "myapp",
]


# ==========================================================
# MIDDLEWARE
# ==========================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ==========================================================
# URLS / WSGI / ASGI
# ==========================================================

ROOT_URLCONF = "myproject.urls"

WSGI_APPLICATION = "myproject.wsgi.application"

ASGI_APPLICATION = "myproject.asgi.application"


# ==========================================================
# TEMPLATES
# ==========================================================

TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends."
            "django.DjangoTemplates"
        ),

        "DIRS":
            [],

        "APP_DIRS":
            True,

        "OPTIONS": {
            "context_processors": [
                (
                    "django.template.context_processors."
                    "request"
                ),
                (
                    "django.contrib.auth."
                    "context_processors.auth"
                ),
                (
                    "django.contrib.messages."
                    "context_processors.messages"
                ),
            ],
        },
    },
]


# ==========================================================
# CHANNEL LAYERS
# ==========================================================

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": (
            "channels.layers."
            "InMemoryChannelLayer"
        ),
    },
}


# ==========================================================
# DATABASE
# ==========================================================

DATABASES = {
    "default": {
        "ENGINE":
            "django.db.backends.sqlite3",

        "NAME":
            BASE_DIR / "db.sqlite3",
    }
}


# ==========================================================
# PASSWORD VALIDATION
# ==========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },

    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# ==========================================================
# INTERNATIONALIZATION
# ==========================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ==========================================================
# EMAIL (OTP)
# ==========================================================

EMAIL_BACKEND = (
    "django.core.mail.backends."
    "smtp.EmailBackend"
)

EMAIL_HOST = "smtp.gmail.com"

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = (
    "bedrockentertainent@gmail.com"
)

EMAIL_HOST_PASSWORD = (
    "zgksulcwmczlqvvm"
)


# ==========================================================
# STATIC & MEDIA FILES
# ==========================================================

STATIC_URL = "/static/"

STATIC_ROOT = (
    BASE_DIR / "staticfiles"
)

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATICFILES_STORAGE = (
    "whitenoise.storage."
    "CompressedManifestStaticFilesStorage"
)

MEDIA_URL = "/media/"

MEDIA_ROOT = (
    BASE_DIR / "media"
)


# ==========================================================
# JAZZMIN — ADMIN THEME CONFIG
# ==========================================================

JAZZMIN_SETTINGS = {

    # ----------------------------------------------
    # BRANDING
    # ----------------------------------------------

    "site_title":
        "Rocks Games Admin",

    "site_header":
        "Rocks Games",

    "site_brand":
        "🎮 Rocks Games",

    "welcome_sign":
        "Welcome to Rocks Games Control Center",

    "copyright":
        "Rocks Games Ltd",

    "site_logo":
        "admin/logo.png",

    "login_logo":
        "admin/logo.png",

    "site_logo_classes":
        "img-circle elevation-2",

    "site_icon":
        "admin/favicon.png",

    # ----------------------------------------------
    # SEARCH
    # ----------------------------------------------

    "search_model": [
        "auth.User",
        "myapp.UserProfileBalance",
    ],

    # ----------------------------------------------
    # TOP MENU
    # ----------------------------------------------

    "topmenu_links": [

        {
            "name":
                "🏠 Dashboard",

            "url":
                "admin:index",

            "permissions":
                ["auth.view_user"],
        },

        {
            "name":
                "💰 Deposits",

            "url": (
                "admin:myapp_depositrequest_"
                "changelist"
            ),
        },

        {
            "name":
                "💸 Withdrawals",

            "url": (
                "admin:myapp_withdrawalrequest_"
                "changelist"
            ),
        },

        {
            "name":
                "👥 Users",

            "url": (
                "admin:myapp_userprofilebalance_"
                "changelist"
            ),
        },

        {
            "name":
                "🎁 Custom Portal",

            "url":
                "/management/",
        },

        {
            "name":
                "📊 Finance",

            "url":
                "/dashboard/finance/",
        },

        {
            "name":
                "🏆 Rewards",

            "url":
                "/management/dashboard/rewards/",
        },

        {
            "name":
                "📈 Analytics",

            "url":
                "/management/dashboard/analytics/",
        },

        {
            "name":
                "📖 Help",

            "url": (
                "https://docs.djangoproject.com/"
                "en/stable/"
            ),

            "new_window":
                True,
        },
    ],

    # ----------------------------------------------
    # USER MENU (top right dropdown)
    # ----------------------------------------------

    "usermenu_links": [

        {
            "name":
                "🎁 Custom Panel",

            "url":
                "/management/",

            "icon":
                "fas fa-gift",
        },

        {
            "name":
                "🏆 Rewards",

            "url":
                "/management/dashboard/rewards/",

            "icon":
                "fas fa-trophy",
        },

        {
            "name":
                "📈 Analytics",

            "url":
                "/management/dashboard/analytics/",

            "icon":
                "fas fa-chart-line",
        },
    ],

    # ----------------------------------------------
    # SIDEBAR
    # ----------------------------------------------

    "show_sidebar":
        True,

    "navigation_expanded":
        True,

    "hide_apps":
        [],

    "hide_models":
        [],

    "order_with_respect_to": [

        "myapp",

        "myapp.UserProfileBalance",
        "myapp.DepositRequest",
        "myapp.WithdrawalRequest",

        "myapp.GameRoom",
        "myapp.GameHistory",
        "myapp.SpinHistory",

        "myapp.ReferralSystem",
        "myapp.SystemTransactionLog",

        "myapp.SystemPaymentMethod",
        "myapp.SystemConfiguration",
        "myapp.SystemSetting",

        "auth",
    ],

    # ----------------------------------------------
    # ICONS
    # ----------------------------------------------

    "icons": {

        "auth":
            "fas fa-users-cog",

        "auth.user":
            "fas fa-user-shield",

        "auth.Group":
            "fas fa-users",

        "myapp":
            "fas fa-gamepad",

        "myapp.UserProfileBalance":
            "fas fa-wallet",

        "myapp.DepositRequest":
            "fas fa-money-bill-wave",

        "myapp.WithdrawalRequest":
            "fas fa-money-bill-transfer",

        "myapp.GameRoom":
            "fas fa-dice",

        "myapp.GameHistory":
            "fas fa-history",

        "myapp.SpinHistory":
            "fas fa-dharmachakra",

        "myapp.ReferralSystem":
            "fas fa-user-friends",

        "myapp.SystemTransactionLog":
            "fas fa-file-invoice-dollar",

        "myapp.SystemPaymentMethod":
            "fas fa-credit-card",

        "myapp.SystemConfiguration":
            "fas fa-sliders-h",

        "myapp.SystemSetting":
            "fas fa-cog",

        "myapp.GameUser":
            "fas fa-user-circle",
    },

    "default_icon_parents":
        "fas fa-chevron-circle-right",

    "default_icon_children":
        "fas fa-circle",

    # ----------------------------------------------
    # CUSTOM CSS / JS
    # ----------------------------------------------

    "custom_css":
        "admin/custom_admin.css",

    "custom_js":
        None,

    # ----------------------------------------------
    # UI BUILDER
    # ----------------------------------------------

    "show_ui_builder":
        False,

    "related_modal_active":
        False,

    # ----------------------------------------------
    # CHANGE FORM
    # ----------------------------------------------

    "changeform_format":
        "horizontal_tabs",

    "changeform_format_overrides": {

        "auth.user":
            "collapsible",

        "auth.group":
            "vertical_tabs",
    },

    # ----------------------------------------------
    # LANGUAGE
    # ----------------------------------------------

    "language_chooser":
        False,
}


# ==========================================================
# JAZZMIN — UI TWEAKS (BLUE + WHITE)
# ==========================================================

JAZZMIN_UI_TWEAKS = {

    "navbar_small_text":
        False,

    "body_small_text":
        False,

    "brand_small_text":
        False,

    "brand_colour":
        "navbar-primary",

    "accent":
        "accent-primary",

    "navbar":
        "navbar-dark",

    "no_navbar_border":
        False,

    "navbar_fixed":
        True,

    "layout_boxed":
        False,

    "footer_fixed":
        False,

    "sidebar_fixed":
        True,

    "sidebar":
        "sidebar-dark-primary",

    "sidebar_nav_small_text":
        False,

    "sidebar_disable_expand":
        False,

    "sidebar_nav_child_indent":
        True,

    "sidebar_nav_compact_style":
        False,

    "sidebar_nav_legacy_style":
        False,

    "sidebar_nav_flat_style":
        True,

    "theme":
        "flatly",

    "default_theme_mode":
        "light",

    "button_classes": {

        "primary":
            "btn-primary",

        "secondary":
            "btn-secondary",

        "info":
            "btn-info",

        "warning":
            "btn-warning",

        "danger":
            "btn-danger",

        "success":
            "btn-success",
    },

    "actions_sticky_top":
        True,
}