"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e3nn6_faorsklka@i7l_y^pu36b^zol-py$ezb#+pi9tn8vebz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# settings.py

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'daphne',
    "jazzmin",   # ← ye sabse upar, django.contrib.admin se PEHLE
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'
ASGI_APPLICATION = 'myproject.asgi.application'

# Multi-client event handling layer
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Email OTP Setup
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'bedrockentertainent@gmail.com'
EMAIL_HOST_PASSWORD = 'zgksulcwmczlqvvm'

# ....................................................................................
# STATIC & MEDIA FILES
# ....................................................................................

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = (
    "whitenoise.storage."
    "CompressedManifestStaticFilesStorage"
)

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ==========================================================
# ALLOWED HOSTS
# ==========================================================

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "192.168.18.48",
]


# ==========================================================
# JAZZMIN ADMIN THEME
# ==========================================================

JAZZMIN_SETTINGS = {

    # ----------------------------------------------
    # BRANDING
    # ----------------------------------------------

    "site_title":
        "Rocks Games Admin",

    "site_header":
        "Rocks Games",

    "site_brand":
        "🎮 Rocks Games",

    "welcome_sign":
        "Welcome to Rocks Games Admin Panel",

    "copyright":
        "Rocks Games Ltd",

    "site_logo":
        None,

    "login_logo":
        None,

    # ----------------------------------------------
    # LAYOUT
    # ----------------------------------------------

    "show_sidebar":
        True,

    "navigation_expanded":
        True,

    "hide_apps":
        [],

    "hide_models":
        [],

    # ----------------------------------------------
    # TOP MENU LINKS
    # ----------------------------------------------

    "topmenu_links": [

        {
            "name":
                "🏠 Home",

            "url":
                "admin:index",

            "permissions":
                ["auth.view_user"],
        },

        {
            "name":
                "⚙️ Custom Panel",

            "url":
                "/management/",
        },

        {
            "name":
                "💰 Finance",

            "url":
                "/dashboard/finance/",
        },

        {
            "name":
                "🎁 Gift Control",

            "url":
                "/management/dashboard/gift/",
        },
    ],

    # ----------------------------------------------
    # ICONS
    # ----------------------------------------------

    "icons": {

        "auth":
            "fas fa-users-cog",

        "auth.user":
            "fas fa-user",

        "auth.Group":
            "fas fa-users",

        "myapp.DepositRequest":
            "fas fa-money-bill-wave",

        "myapp.WithdrawalRequest":
            "fas fa-money-bill-transfer",

        "myapp.UserProfileBalance":
            "fas fa-wallet",

        "myapp.SystemPaymentMethod":
            "fas fa-credit-card",

        "myapp.GameRoom":
            "fas fa-dice",

        "myapp.SystemTransactionLog":
            "fas fa-history",

        "myapp.ReferralSystem":
            "fas fa-user-friends",

        "myapp.SystemSetting":
            "fas fa-cog",

        "myapp.SystemConfiguration":
            "fas fa-sliders-h",

        "myapp.GameUser":
            "fas fa-gamepad",
    },

    # ----------------------------------------------
    # THEME
    # ----------------------------------------------

    "theme":
        "darkly",
}


# ==========================================================
# JAZZMIN UI TWEAKS
# ==========================================================

JAZZMIN_UI_TWEAKS = {

    "navbar_small_text":
        False,

    "body_small_text":
        False,

    "brand_small_text":
        False,

    "brand_colour":
        "navbar-danger",

    "accent":
        "accent-warning",

    "navbar":
        "navbar-dark",

    "no_navbar_border":
        False,

    "navbar_fixed":
        True,

    "layout_boxed":
        False,

    "footer_fixed":
        False,

    "sidebar_fixed":
        True,

    "sidebar":
        "sidebar-dark-danger",

    "sidebar_nav_small_text":
        False,

    "sidebar_disable_expand":
        False,

    "sidebar_nav_child_indent":
        True,

    "sidebar_nav_compact_style":
        False,

    "sidebar_nav_legacy_style":
        False,

    "sidebar_nav_flat_style":
        True,

    "theme":
        "darkly",

    "dark_mode_theme":
        "darkly",

    "button_classes": {

        "primary":
            "btn-primary",

        "secondary":
            "btn-secondary",

        "info":
            "btn-info",

        "warning":
            "btn-warning",

        "danger":
            "btn-danger",

        "success":
            "btn-success",
    },
}