# Generated by Django 6.1 on 2026-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_gameuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebalance',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
