# Generated by Django 6.1 on 2026-09-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userprofilebalance_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilebalance',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userprofilebalance',
            name='email',
            field=models.EmailField(blank=True, help_text='User email.', max_length=254, null=True, unique=True),
        ),
    ]
