# Generated by Django 6.1 on 2026-09-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_userprofilebalance_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Unique configuration identifier key.', max_length=100, unique=True)),
                ('value', models.CharField(blank=True, default='', help_text='Stored configuration value payload.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last configuration mutation timestamp.')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
