# Generated by Django 6.1 on 2026-09-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebalance',
            name='last_free_spin',
            field=models.BigIntegerField(default=0, help_text='Timestamp of last free spin in seconds'),
        ),
    ]
