# Generated by Django 6.1 on 2026-09-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_systempaymentmethod_method_type_and_more'),
        ('myapp', '0012_userprofilebalance_last_free_spin'),
    ]

    operations = [
    ]
