# Generated by Django 6.1 on 2026-09-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_merge_20260928_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_private',
            field=models.BooleanField(default=False, help_text='True for friend-invite rooms with shareable code.'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='room_code',
            field=models.CharField(blank=True, db_index=True, help_text='Short shareable code for private rooms.', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='service_fee_cut',
            field=models.IntegerField(default=0, help_text='System administration platform tax.'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='winner_payout',
            field=models.IntegerField(default=0, help_text='Delivery distribution payload sum.'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='device_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systempaymentmethod',
            name='method_type',
            field=models.CharField(choices=[('JAZZCASH', 'JazzCash'), ('EASYPAISA', 'EasyPaisa'), ('BINANCE', 'Binance')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='systemtransactionlog',
            name='log_type',
            field=models.CharField(choices=[('DEPOSIT', 'Manual Deposit Inflow'), ('WITHDRAWAL', 'Manual Withdrawal Outflow'), ('WAGER_ESCROW', 'Match Entry Lock'), ('WAGER_PAYOUT', 'Match Win Distribution'), ('WAGER_REFUND', 'Match Entry Refund'), ('REFERRAL_BONUS', 'Onboarding Sign-up Bonus'), ('REFERRAL_COMMISSION', 'Dynamic Withdrawal Bonus Reward'), ('SPIN_COST', 'Lucky Spin Paid Cost'), ('SPIN_REWARD', 'Lucky Spin Reward')], max_length=25),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='method',
            field=models.CharField(choices=[('JAZZCASH', 'JazzCash'), ('EASYPAISA', 'EasyPaisa'), ('BINANCE', 'Binance')], max_length=20),
        ),
    ]
