# Generated by Django 6.1 on 2026-09-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_gameroom_is_private_gameroom_room_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='max_players',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of players allowed in this room (2 or 4).'),
        ),
    ]
