# Generated by Django 6.1 on 2026-09-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_gameroom_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebalance',
            name='has_withdrawal_pin',
            field=models.BooleanField(default=False, help_text='True once the user sets a 4-digit withdrawal PIN.'),
        ),
        migrations.AddField(
            model_name='userprofilebalance',
            name='withdrawal_pin_hash',
            field=models.CharField(blank=True, help_text='Hashed withdrawal PIN (Django password hash).', max_length=128, null=True),
        ),
    ]
