# Generated by Django 6.1 on 2026-09-30 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_userprofilebalance_has_withdrawal_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebalance',
            name='last_daily_bonus',
            field=models.BigIntegerField(default=0, help_text='Timestamp of last daily bonus claim (seconds).'),
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(db_index=True, max_length=100)),
                ('bet_amount', models.IntegerField(default=0)),
                ('result', models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('CANCELLED', 'Cancelled'), ('SURRENDERED', 'Surrendered')], max_length=20)),
                ('coins_change', models.IntegerField(default=0, help_text='Net coins gained (+) or lost (-) by this player in this game.')),
                ('game_mode', models.CharField(choices=[('2P', 'Two Player'), ('4P', 'Four Player')], default='2P', max_length=5)),
                ('opponent_count', models.PositiveIntegerField(default=1)),
                ('played_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_history', to='myapp.userprofilebalance')),
            ],
            options={
                'verbose_name': 'Game History',
                'verbose_name_plural': 'Game History',
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['user_profile', '-played_at'], name='myapp_gameh_user_pr_8641f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpinHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_name', models.CharField(max_length=50)),
                ('gift_emoji', models.CharField(default='🎁', max_length=10)),
                ('coin_value', models.IntegerField(default=0, help_text='Coins won in this spin (0 for non-coin prizes).')),
                ('was_free', models.BooleanField(default=True)),
                ('cost_paid', models.IntegerField(default=0, help_text='Coins spent on this spin (0 if free).')),
                ('spun_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_history', to='myapp.userprofilebalance')),
            ],
            options={
                'verbose_name': 'Spin History',
                'verbose_name_plural': 'Spin History',
                'ordering': ['-spun_at'],
                'indexes': [models.Index(fields=['user_profile', '-spun_at'], name='myapp_spinh_user_pr_35bebc_idx')],
            },
        ),
    ]
