# Generated by Django 6.1 on 2026-10-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_userprofilebalance_last_daily_bonus_gamehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralsystem',
            name='referrer_reward_amount',
            field=models.PositiveIntegerField(default=0, help_text='Amount credited to referrer on first deposit.'),
        ),
        migrations.AddField(
            model_name='referralsystem',
            name='referrer_reward_paid',
            field=models.BooleanField(default=False, help_text="True when the referrer has been credited for this invite (after referred user's first deposit)."),
        ),
        migrations.AddField(
            model_name='userprofilebalance',
            name='has_made_first_deposit',
            field=models.BooleanField(default=False, help_text='True once this user has had at least one deposit approved. Used to trigger referrer reward on first deposit.'),
        ),
        migrations.AlterField(
            model_name='systemtransactionlog',
            name='log_type',
            field=models.CharField(choices=[('DEPOSIT', 'Manual Deposit Inflow'), ('WITHDRAWAL', 'Manual Withdrawal Outflow'), ('WAGER_ESCROW', 'Match Entry Lock'), ('WAGER_PAYOUT', 'Match Win Distribution'), ('WAGER_REFUND', 'Match Entry Refund'), ('REFERRAL_BONUS', 'Onboarding Sign-up Bonus'), ('REFERRAL_COMMISSION', 'Dynamic Withdrawal Bonus Reward'), ('REFERRAL_INVITE_REWARD', 'Referrer first-deposit reward'), ('SPIN_COST', 'Lucky Spin Paid Cost'), ('SPIN_REWARD', 'Lucky Spin Reward'), ('LEADERBOARD_REWARD', 'Leaderboard Reward')], max_length=30),
        ),
    ]
