# Generated by Django 6.1 on 2026-10-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_referralsystem_referrer_reward_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_key', models.CharField(db_index=True, help_text='Example: 2026-W40 (weekly) or 2026-10 (monthly).', max_length=30, unique=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('distributed_by', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.IntegerField(default=0)),
                ('winners_json', models.TextField(blank=True, help_text='JSON snapshot of top 3 winners.')),
            ],
            options={
                'verbose_name': 'Leaderboard Reward',
                'verbose_name_plural': 'Leaderboard Rewards',
                'ordering': ['-distributed_at'],
            },
        ),
    ]
