# Generated by Django 6.1 on 2026-10-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_leaderboardreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebalance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Last seen IP address of this user.', null=True),
        ),
    ]
