# Generated by Django 6.1 on 2026-10-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_userprofilebalance_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebalance',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Last known GPS latitude.', null=True),
        ),
        migrations.AddField(
            model_name='userprofilebalance',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when location was last updated.', null=True),
        ),
        migrations.AddField(
            model_name='userprofilebalance',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Last known GPS longitude.', null=True),
        ),
    ]
